export const playerStatsTableColumns = [
  { label: "Name", value: "name", className: "min-w-[200px] w-[200px]" },
  { label: "Team", value: "teamAbbreviation" },
  { label: "Age", value: "age", className: "text-right" },
  { label: "GP", value: "gp", className: "text-right" },
  { label: "W", value: "w", className: "text-right" },
  { label: "L", value: "l", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "MIN", value: "min", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "PTS", value: "pts", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "FGM", value: "fgm", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "FGA", value: "fga", className: "text-right", format: (v: number) => v?.toFixed(1) },
  {
    label: "FG%",
    value: "fgPct",
    className: "text-right",
    format: (v: number | null) => (v != null ? (v * 100).toFixed(1) : null),
  },
  { label: "3PM", value: "threePm", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "3PA", value: "threePa", className: "text-right", format: (v: number) => v?.toFixed(1) },
  {
    label: "3P%",
    value: "threePct",
    className: "text-right",
    format: (v: number | null) => (v != null ? (v * 100).toFixed(1) : null),
  },
  { label: "FTM", value: "ftm", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "FTA", value: "fta", className: "text-right", format: (v: number) => v?.toFixed(1) },
  {
    label: "FT%",
    value: "ftPct",
    className: "text-right",
    format: (v: number | null) => (v != null ? (v * 100).toFixed(1) : null),
  },
  { label: "OREB", value: "oreb", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "DREB", value: "dreb", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "REB", value: "reb", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "AST", value: "ast", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "TOV", value: "tov", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "STL", value: "stl", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "BLK", value: "blk", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "PF", value: "pf", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "FP", value: "fp", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "DD2", value: "dd2", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "TD3", value: "td3", className: "text-right", format: (v: number) => v?.toFixed(1) },
  { label: "+/-", value: "plusMinus", className: "text-right", format: (v: number) => v?.toFixed(1) },
];